//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailsysteem_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BerichtOntvanger
    {
        public int id { get; set; }
        public int berichtId { get; set; }
        public int gebruikerId { get; set; }
        public bool isCC { get; set; }
    
        public virtual Bericht Bericht { get; set; }
        public virtual Gebruiker Gebruiker { get; set; }
    }
}
