//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailsysteem_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bericht
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bericht()
        {
            this.BerichtOntvanger = new HashSet<BerichtOntvanger>();
        }
    
        public int id { get; set; }
        public string onderwerp { get; set; }
        public System.DateTime datumVerstuurd { get; set; }
        public string berichtTekst { get; set; }
        public string bijlage { get; set; }
        public Nullable<int> verzenderId { get; set; }
        public bool isVerwijderd { get; set; }
    
        public virtual Gebruiker Gebruiker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BerichtOntvanger> BerichtOntvanger { get; set; }
    }
}
