//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailsysteem_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaakCategorie
    {
        public int id { get; set; }
        public int taakId { get; set; }
        public int categorieId { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual Taak Taak { get; set; }
    }
}
