//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailsysteem_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taak
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Taak()
        {
            this.TaakCategorie = new HashSet<TaakCategorie>();
        }
    
        public int id { get; set; }
        public string naam { get; set; }
        public bool isVoltooid { get; set; }
        public Nullable<System.DateTime> herinneringDatum { get; set; }
        public System.DateTime eindDatum { get; set; }
        public int gebruikerId { get; set; }
        public string extraInfo { get; set; }
    
        public virtual Gebruiker Gebruiker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaakCategorie> TaakCategorie { get; set; }
    }
}
