//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailsysteem_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vergadering
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vergadering()
        {
            this.VergaderingGenodigde = new HashSet<VergaderingGenodigde>();
        }
    
        public int id { get; set; }
        public string onderwerp { get; set; }
        public Nullable<int> organisatorId { get; set; }
        public System.DateTime datum { get; set; }
        public string plaats { get; set; }
        public System.TimeSpan beginTijd { get; set; }
        public System.TimeSpan eindTijd { get; set; }
    
        public virtual Gebruiker Gebruiker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VergaderingGenodigde> VergaderingGenodigde { get; set; }
    }
}
